### ISSUE TITLE
How to change of font size

### ISSUE THREAD

**Issue by shilik** [helephant/Gem#6]
Well, I have found the solution. no need to find a quick fix. :P

**Comment by helephant** [comment]
What did you do in the end? :)

Also I’m really thrilled you’re using my library!

**Comment by shilik** [comment]
Well, I added the following codes before `<font size='6'>` as a workaround.
`<meta name='viewport' content='width=device-width, initial-scale=1.0'>`
Your awesome plugin has saved me a lot of time for ruby-text of Chinese and Japanese languages.
Thanks again. GJ! @helephant
